### ISSUE TITLE
[Bug]: parallel write-out to netcdf fails in tests

### ISSUE THREAD

**Issue by ClaudiaComito** [helmholtz-analytics/heat#1071]
### What happened?

Our own tests (`test_io.test_save`) fail when parallel netCDF is enabled. 

Tested on HDFML cluster with Stage 2022 stack and `netcdf4-python` module. 

```
ml Stages/2022
ml GCC
ml CUDA
ml OpenMPI
ml mpi4py
ml PyTorch
ml torchvision
ml HDF5
ml h5py
ml netCDF
ml netcdf4-python  
```

### Error message or erroneous outcome

```shell
Traceback (most recent call last):
  File "/p/project/haf/users/comito1/devel/heat/heat/core/tests/test_io.py", line 299, in test_save
    local_range.save(self.NETCDF_OUT_PATH, self.NETCDF_VARIABLE)
  File "/p/project/haf/users/comito1/devel/heat/heat/core/io.py", line 1110, in <lambda>
    DNDarray.save = lambda self, path, *args, **kwargs: save(self, path, *args, **kwargs)
  File "/p/project/haf/users/comito1/devel/heat/heat/core/io.py", line 1101, in save
    save_netcdf(data, path, *args, **kwargs)
  File "/p/project/haf/users/comito1/devel/heat/heat/core/io.py", line 649, in save_netcdf
    raise excep
  File "/p/project/haf/users/comito1/devel/heat/heat/core/io.py", line 588, in save_netcdf
    var[merged_slices] = (
  File "src/netCDF4/_netCDF4.pyx", line 4945, in netCDF4._netCDF4.Variable.__setitem__
  File "src/netCDF4/_netCDF4.pyx", line 5204, in netCDF4._netCDF4.Variable._put
IndexError: size of data array does not conform to slice
```

### Version

1.2.x

### Python version

3.9

### PyTorch version

1.11

### MPI version

```shell
OpenMPI 4.1.2
```

**Comment by ClaudiaComito** [comment]
Reproduction with OpenMPI 4.1.2 requires bug fix #1058
