### ISSUE TITLE
[Bug]: Bug in `Gather` if non-used receive-buffers are set to `None`

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1174]
### What happened?

Using `comm.Gather` with `recv_buf=None` for the non-receiving processes fails. 

### Code snippet triggering the error

```shell
import heat as ht
from mpi4py import MPI
import torch

x = ht.ones((2*MPI.COMM_WORLD.Get_size(),3,4),split=0,device="gpu")
x.larray *= x.comm.rank

print(x.comm.rank, x.larray)

send_buf = x
if x.comm.rank == 0:
    recv_buf = torch.zeros(2*MPI.COMM_WORLD.Get_size(),3,4,device=x.larray.device)
else:
    recv_buf = None
x.comm.Gather(send_buf,recv_buf)

print(x.comm.rank, recv_buf)                    
```

Note that the same routine avoiding `None`'s does not fail, e.g.: 
```
send_buf = x
recv_buf = torch.zeros(2,3*MPI.COMM_WORLD.Get_size(),4,device=x.larray.device)
x.comm.Gather(send_buf,recv_buf)

```
yields the expected outcome, but consumes much more memory.

### Error message or erroneous outcome

```shell
Traceback (most recent call last):
  File "test_print.py", line 24, in <module>
    x.comm.Gather(send_buf,recv_buf)
  File "******************/heat/heat/core/communication.py", line 1606, in Gather
    ret, sbuf, rbuf, buf, permutation = self.__scatter_like(
  File ""******************//heat/heat/core/communication.py", line 1546, in __scatter_like
    send_axis_permutation = list(range(recvbuf.ndimension()))
AttributeError: 'NoneType' object has no attribute 'ndimension'
```

**Comment by mrfh92** [comment]
@mtar or is this the intended behaviour and Im just too stupid to understand it?

**Comment by mtar** [comment]
You may want to use a 0 sized tensor like torch.empty(0) on the other processes.
