### ISSUE TITLE
[Bug]: Lasso does not work on GPU 

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1258]
### What happened?

Lasso throws an error when used on GPU; on CPU everything works fine. 

### Code snippet triggering the error

```shell
import heat as ht 

device='gpu'
A = ht.random.randn(100,100,dtype=ht.float32,split=0,device=device)
b = ht.random.randn(100,dtype=ht.float32,split=0,device=device)

regressor = ht.regression.Lasso()
regressor.fit(A,b)
```
```


### Error message or erroneous outcome

```shell
Traceback (most recent call last):
  File "lasso.py", line 8, in <module>
    regressor.fit(A,b)
  File "/home/hopp_fa/heat/heat/regression/lasso.py", line 157, in fit
    rho = (X_j * (y - y_est + theta_j * X_j)).mean()
  File "/home/hopp_fa/heat/heat/core/arithmetics.py", line 121, in _add
    return add(self, other)
  File "/home/hopp_fa/heat/heat/core/arithmetics.py", line 116, in add
    return _operations.__binary_op(torch.add, t1, t2, out, where)
  File "/home/hopp_fa/heat/heat/core/_operations.py", line 174, in __binary_op
    result = operation(t1.larray.to(promoted_type), t2.larray.to(promoted_type), **fn_kwargs)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!
```

### Version

main (development branch)

### Python version

3.8, 3.10

### PyTorch version

2.0

### MPI version

OpenMPI

**Comment by mrfh92** [comment]
Bug fix has been merged in release and main.
