### ISSUE TITLE
[Bug]: `solve_triangular` fails in unit tests on `main`

### ISSUE THREAD

**Issue by mrfh92** [helmholtz-analytics/heat#1433]
### What happened?

On my workstation, the tests for `solve_triangular` fail on `main`

### Code snippet triggering the error

```shell
mpirun -n 2 python -m unittest heat/core/linalg/tests/test_solver.py
```

### Error message or erroneous outcome

```shell
======================================================================
ERROR: test_solve_triangular (heat.core.linalg.tests.test_solver.TestSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/hopp_fa/heat/heat/core/linalg/tests/test_solver.py", line 162, in test_solve_triangular
    res = ht.linalg.solve_triangular(a, b)
  File "/home/hopp_fa/heat/heat/core/linalg/solver.py", line 453, in solve_triangular
    comm.Bcast(x_from_i, root=i)
  File "/home/hopp_fa/heat/heat/core/communication.py", line 747, in Bcast
    ret, sbuf, rbuf, buf = self.__broadcast_like(self.handle.Bcast, buf, root)
  File "/home/hopp_fa/heat/heat/core/communication.py", line 734, in __broadcast_like
    return func(self.as_buffer(srbuf), root), srbuf, srbuf, buf
  File "mpi4py/MPI/Comm.pyx", line 691, in mpi4py.MPI.Comm.Bcast
mpi4py.MPI.Exception: MPI_ERR_TRUNCATE: message truncated
```

### Versions

Heat: dev (main branch)
Python: 3.10.13
PyTorch: 2.2.0+cu118
MPI: mpi4py 3.1.6, OpenMPI 4.0.3

**Comment by mrfh92** [comment]
On Terrabyte I obtain 
```
======================================================================
FAIL: test_solve_triangular (heat.core.linalg.tests.test_solver.TestSolver)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/dss/dsshome1/03/di93zek/heat/heat/core/linalg/tests/test_solver.py", line 224, in test_solve_triangular
    self.assertTrue(ht.allclose(c, res))
AssertionError: False is not true
```
