### ISSUE TITLE
tril() in distributed mode

### ISSUE THREAD

**Issue by krajsek** [helmholtz-analytics/heat#147]
tril() does not catch the case of #ranks> dimension of tensor.

Example:
mpirun -n 4 test.py

test.py:
import heat as ht
distributed_ones = ht.ones((3,), split=0
result = distributed_ones.tril()

error message:
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    result = distributed_ones.tril()
  File "/home/kk/JSC/projects/HAF/software/heat/heat/core/tensor.py", line 657, in tril
    return operations.tril(self, k)
  File "/home/kk/JSC/projects/HAF/software/heat/heat/core/operations.py", line 666, in tril
    return __tri_op(m, k, torch.tril)
  File "/home/kk/JSC/projects/HAF/software/heat/heat/core/operations.py", line 611, in __tri_op
    triangle = op(m._tensor__array.expand(m.shape[0], -1), k - offset)
RuntimeError: invalid argument 1: expected a matrix at /opt/conda/conda-bld/pytorch-cpu_1544218188686/work/aten/src/TH/generic/THTensorMoreMath.cpp:1255

**Comment by Markus-Goetz** [comment]
Remove the size constraints in the triu and tril test cases introduced in PR #189
